-- MySQL Script generated by MySQL Workbench
-- Sat Feb  7 10:52:47 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logitrack
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logitrack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logitrack` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `logitrack` ;

-- -----------------------------------------------------
-- Table `logitrack`.`carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logitrack`.`carrier` (
  `carrier_id` INT NOT NULL AUTO_INCREMENT,
  `carrier_name` VARCHAR(45) NOT NULL,
  `carrier_cnpj` VARCHAR(45) NOT NULL,
  `carrier_logical_status` INT NOT NULL,
  PRIMARY KEY (`carrier_id`),
  UNIQUE INDEX `carrier_cnpj_UNIQUE` (`carrier_cnpj` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `logitrack`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logitrack`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `logitrack`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logitrack`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(25) NULL DEFAULT NULL,
  `user_email` VARCHAR(25) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_logical_status` INT NOT NULL,
  `carrier_id` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_carrier1_idx` (`carrier_id` ASC),
  CONSTRAINT `fk_user_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `logitrack`.`carrier` (`carrier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `logitrack`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logitrack`.`vehicle` (
  `vehicle_id` INT NOT NULL AUTO_INCREMENT,
  `vehicle_plate` VARCHAR(45) NOT NULL,
  `vehicle_model` VARCHAR(45) NOT NULL,
  `vehicle_driver_name` VARCHAR(45) NULL DEFAULT NULL,
  `vehicle_capacity` VARCHAR(45) NOT NULL,
  `vehicle_status` INT NOT NULL,
  `vehicle_logical_status` INT NOT NULL,
  `carrier_id` INT NOT NULL,
  PRIMARY KEY (`vehicle_id`),
  INDEX `fk_vehicle_carrier1_idx` (`carrier_id` ASC),
  CONSTRAINT `fk_vehicle_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `logitrack`.`carrier` (`carrier_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `logitrack`.`status_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logitrack`.`status_history` (
  `status_history_id` INT NOT NULL AUTO_INCREMENT,
  `status_history_previous` INT NULL DEFAULT NULL,
  `status_history_new` INT NULL DEFAULT NULL,
  `status_history_date` DATE NULL DEFAULT NULL,
  `status_history_logical_status` INT NOT NULL,
  `vehicle_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `carrier_id` INT NOT NULL,
  PRIMARY KEY (`status_history_id`),
  INDEX `fk_status_history_vehicle1_idx` (`vehicle_id` ASC),
  INDEX `fk_status_history_user1_idx` (`user_id` ASC),
  INDEX `fk_status_history_carrier1_idx` (`carrier_id` ASC),
  CONSTRAINT `fk_status_history_carrier1`
    FOREIGN KEY (`carrier_id`)
    REFERENCES `logitrack`.`carrier` (`carrier_id`),
  CONSTRAINT `fk_status_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `logitrack`.`user` (`user_id`),
  CONSTRAINT `fk_status_history_vehicle1`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `logitrack`.`vehicle` (`vehicle_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `logitrack`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logitrack`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `fk_user_role_user1_idx` (`user_id` ASC),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `logitrack`.`role` (`role_id`),
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `logitrack`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
